export interface ComponentItem {
  id: string
  name: string
  category: string
  description: string
  tags: string[]
  code: string
  preview?: React.ComponentType<any>
  gradient?: boolean
  morphing?: boolean
  micro?: boolean
}

export const allComponents: ComponentItem[] = [
  {
    id: "pulse-button",
    name: "Pulse Button",
    category: "Micro-interactions",
    description: "A button with hover pulse effect and gradient background",
    tags: ["hover","animation","button","gradient"],
    code: "'use client'\n\nimport { motion } from 'framer-motion'\nimport { useState } from 'react'\nimport { Menu, X } from 'lucide-react'\n\nexport function PulseButton() {\n  const [isHovered, setIsHovered] = useState(false)\n\n  return (\n    <motion.button\n      onMouseEnter={() => setIsHovered(true)}\n      onMouseLeave={() => setIsHovered(false)}\n      className=\"px-8 py-3 bg-yellow-500 dark:bg-yellow-600 text-black rounded-full font-semibold relative overflow-hidden\"\n      whileHover={{ scale: 1.05 }}\n      whileTap={{ scale: 0.95 }}\n    >\n      {isHovered && (\n        <motion.div\n          className=\"absolute inset-0 bg-black/10\"\n          initial={{ opacity: 0 }}\n          animate={{ opacity: 1 }}\n          exit={{ opacity: 0 }}\n          transition={{ duration: 0.3 }}\n        />\n      )}\n      <span className=\"relative z-10\">Hover Me</span>\n    </motion.button>\n  )\n}",
    gradient: true,
    micro: true,
  },
  {
    id: "morph-card",
    name: "Morphing Card",
    category: "Morphing Shapes",
    description: "A card that morphs between different shapes with smooth animation",
    tags: ["morph","shape","animation"],
    code: "'use client'\n\nimport { motion } from 'framer-motion'\nimport { useState } from 'react'\nimport { Menu, X } from 'lucide-react'\n\nexport function MorphCard() {\n  return (\n    <motion.div\n      className=\"w-64 h-64 bg-gradient-to-br from-blue-500 to-cyan-500 cursor-pointer\"\n      animate={{\n        borderRadius: ['60% 40% 30% 70% / 60% 30% 70% 40%', '30% 60% 70% 40% / 50% 60% 30% 60%', '60% 40% 30% 70% / 60% 30% 70% 40%']\n      }}\n      transition={{ duration: 4, repeat: Infinity }}\n      whileHover={{ scale: 1.1 }}\n    />\n  )\n}",
    morphing: true,
  },
  {
    id: "gradient-text",
    name: "Animated Gradient Text",
    category: "Gradient Effects",
    description: "Text with animated gradient that flows smoothly",
    tags: ["gradient","text","animation"],
    code: "'use client'\n\nimport { motion } from 'framer-motion'\nimport { useState } from 'react'\nimport { Menu, X } from 'lucide-react'\n\nexport function GradientText() {\n  return (\n    <motion.div\n      className=\"text-4xl font-bold bg-gradient-to-r from-purple-400 via-pink-500 to-orange-400 bg-clip-text text-transparent\"\n      animate={{\n        backgroundPosition: ['0%', '100%', '0%']\n      }}\n      transition={{ duration: 3, repeat: Infinity }}\n      style={{\n        backgroundSize: '200% 200%'\n      }}\n    >\n      Animated Gradient\n    </motion.div>\n  )\n}",
    gradient: true,
  },
  {
    id: "ripple-button",
    name: "Ripple Button",
    category: "Micro-interactions",
    description: "Button with material design ripple effect on click",
    tags: ["ripple","click","animation","button"],
    code: "'use client'\n\nimport { motion } from 'framer-motion'\nimport { useState } from 'react'\nimport { Menu, X } from 'lucide-react'\n\nexport function RippleButton() {\n  const [ripples, setRipples] = useState<RippleItem[]>([])\n\n  const handleClick = (e: React.MouseEvent<HTMLButtonElement>) => {\n    const rect = e.currentTarget.getBoundingClientRect()\n    const x = e.clientX - rect.left\n    const y = e.clientY - rect.top\n    const newRipple = { x, y, id: Date.now() }\n    \n    setRipples(prev => [...prev, newRipple])\n    setTimeout(() => {\n      setRipples(prev => prev.filter(r => r.id !== newRipple.id))\n    }, 600)\n  }\n\n  return (\n    <motion.button\n      onClick={handleClick}\n      className=\"px-6 py-3 bg-yellow-500 dark:bg-yellow-600 text-black rounded-lg font-semibold relative overflow-hidden\"\n      whileHover={{ backgroundColor: '#ca8a04' }}\n    >\n      {ripples.map(ripple => (\n        <motion.span\n          key={ripple.id}\n          className=\"absolute w-2 h-2 bg-white rounded-full pointer-events-none\"\n          style={{ left: ripple.x, top: ripple.y }}\n          initial={{ width: 8, height: 8, opacity: 0.8 }}\n          animate={{ width: 400, height: 400, opacity: 0 }}\n          transition={{ duration: 0.6 }}\n        />\n      ))}\n      Click Me\n    </motion.button>\n  )\n}",
    micro: true,
  },
  {
    id: "floating-card",
    name: "Floating Card",
    category: "Micro-interactions",
    description: "A card that floats up and down with hover effects",
    tags: ["float","hover","animation"],
    code: "'use client'\n\nimport { motion } from 'framer-motion'\nimport { useState } from 'react'\nimport { Menu, X } from 'lucide-react'\n\nexport function FloatingCard() {\n  return (\n    <motion.div\n      className=\"w-56 h-56 bg-gradient-to-br from-emerald-400 to-cyan-500 rounded-2xl shadow-2xl\"\n      animate={{ y: [0, -20, 0] }}\n      transition={{ duration: 3, repeat: Infinity, ease: 'easeInOut' }}\n      whileHover={{ scale: 1.05, boxShadow: '0 20px 40px rgba(16, 185, 129, 0.4)' }}\n    >\n      <div className=\"w-full h-full flex items-center justify-center\">\n        <div className=\"text-white text-center\">\n          <p className=\"text-sm opacity-80\">Floating Card</p>\n          <p className=\"text-2xl font-bold\">Hover Me</p>\n        </div>\n      </div>\n    </motion.div>\n  )\n}",
    micro: true,
  },
  {
    id: "glass-button",
    name: "Glassmorphism Button",
    category: "Gradient Effects",
    description: "A button with glassmorphism design effect",
    tags: ["glass","blur","modern"],
    code: "'use client'\n\nimport { motion } from 'framer-motion'\nimport { useState } from 'react'\nimport { Menu, X } from 'lucide-react'\n\nexport function GlassButton() {\n  return (\n    <div className=\"relative\">\n      <div className=\"absolute inset-0 bg-gradient-to-r from-blue-500 to-purple-500 rounded-xl blur-lg opacity-75\" />\n      <motion.button\n        className=\"relative px-8 py-3 rounded-xl backdrop-blur-md bg-white/10 border border-white/30 text-white font-semibold\"\n        whileHover={{\n          backgroundColor: 'rgba(255, 255, 255, 0.2)',\n          borderColor: 'rgba(255, 255, 255, 0.5)'\n        }}\n        whileTap={{ scale: 0.95 }}\n      >\n        Glassmorphism\n      </motion.button>\n    </div>\n  )\n}",
    gradient: true,
  },
  {
    id: "shimmer-text",
    name: "Shimmer Text",
    category: "Gradient Effects",
    description: "Text with a shimmering animation effect",
    tags: ["shimmer","gradient","text"],
    code: "'use client'\n\nimport { motion } from 'framer-motion'\nimport { useState } from 'react'\nimport { Menu, X } from 'lucide-react'\n\nexport function ShimmerText() {\n  return (\n    <div className=\"relative inline-block\">\n      <motion.div \n        className=\"text-3xl font-bold\"\n        animate={{\n          backgroundPosition: ['0%', '100%', '0%']\n        }}\n        transition={{ duration: 3, repeat: Infinity }}\n        style={{\n          background: 'linear-gradient(90deg, #1f2937, #8b5cf6, #1f2937)',\n          backgroundSize: '200% 100%',\n          WebkitBackgroundClip: 'text',\n          WebkitTextFillColor: 'transparent',\n          backgroundClip: 'text',\n        }}\n      >\n        Shimmer Effect\n      </motion.div>\n    </div>\n  )\n}",
    gradient: true,
  },
  {
    id: "expandable-card",
    name: "Expandable Card",
    category: "Micro-interactions",
    description: "A card that expands and collapses on click",
    tags: ["expand","animation","layout"],
    code: "'use client'\n\nimport { motion } from 'framer-motion'\nimport { useState } from 'react'\nimport { Menu, X } from 'lucide-react'\n\nexport function ExpandableCard() {\n  const [isExpanded, setIsExpanded] = useState(false)\n\n  return (\n    <motion.div\n      layout\n      onClick={() => setIsExpanded(!isExpanded)}\n      className=\"w-64 bg-gradient-to-br from-violet-600 to-fuchsia-600 rounded-2xl p-6 cursor-pointer text-white\"\n      initial={{ borderRadius: 16 }}\n      animate={{ borderRadius: isExpanded ? 24 : 16 }}\n    >\n      <h3 className=\"text-xl font-bold mb-4\">Expandable Card</h3>\n      {isExpanded && (\n        <motion.div\n          initial={{ opacity: 0, height: 0 }}\n          animate={{ opacity: 1, height: 'auto' }}\n          exit={{ opacity: 0, height: 0 }}\n          className=\"text-sm opacity-90\"\n        >\n          Click me again to collapse. This card expands smoothly with animation!\n        </motion.div>\n      )}\n    </motion.div>\n  )\n}",
    micro: true,
  },
  {
    id: "orbital-button",
    name: "Orbital Button",
    category: "Morphing Shapes",
    description: "A button surrounded by orbiting circles",
    tags: ["orbital","animation","shapes"],
    code: "'use client'\n\nimport { motion } from 'framer-motion'\nimport { useState } from 'react'\nimport { Menu, X } from 'lucide-react'\n\nexport function OrbitalButton() {\n  const orbits = [1, 2, 3]\n\n  return (\n    <div className=\"relative w-40 h-40 flex items-center justify-center\">\n      {orbits.map((orbit) => (\n        <motion.div\n          key={orbit}\n          className=\"absolute border border-purple-500/30 rounded-full\"\n          animate={{ rotate: 360 }}\n          transition={{\n            duration: 10 + orbit * 5,\n            repeat: Infinity,\n            ease: 'linear'\n          }}\n          style={{ width: 32 * orbit, height: 32 * orbit }}\n        />\n      ))}\n      <motion.button\n        className=\"relative z-10 px-6 py-2 bg-purple-600 text-white rounded-full font-semibold\"\n        whileHover={{ scale: 1.1 }}\n        whileTap={{ scale: 0.95 }}\n      >\n        Center\n      </motion.button>\n    </div>\n  )\n}",
    morphing: true,
  },
  {
    id: "slide-in-menu",
    name: "Slide-in Menu",
    category: "Micro-interactions",
    description: "A menu that slides in from the side with smooth animation",
    tags: ["menu","slide","animation","navigation"],
    code: "'use client'\n\nimport { motion } from 'framer-motion'\nimport { useState } from 'react'\nimport { Menu, X } from 'lucide-react'\n\nexport function SlideInMenu() {\n  const [isOpen, setIsOpen] = useState(false)\n\n  return (\n    <div className=\"relative\">\n      <motion.button\n        onClick={() => setIsOpen(!isOpen)}\n        className=\"p-2 rounded-lg bg-purple-600 text-white\"\n        whileTap={{ scale: 0.95 }}\n      >\n        {isOpen ? <X size={24} /> : <Menu size={24} />}\n      </motion.button>\n\n      {isOpen && (\n        <motion.div\n          initial={{ x: -300, opacity: 0 }}\n          animate={{ x: 0, opacity: 1 }}\n          exit={{ x: -300, opacity: 0 }}\n          transition={{ type: 'spring', stiffness: 300, damping: 30 }}\n          className=\"absolute top-12 left-0 w-64 bg-gray-900 rounded-r-lg p-6 space-y-4 z-50\"\n        >\n          {['Home', 'About', 'Services', 'Contact'].map((item) => (\n            <motion.a\n              key={item}\n              href=\"#\"\n              className=\"block text-white hover:text-purple-400\"\n              whileHover={{ x: 10 }}\n            >\n              {item}\n            </motion.a>\n          ))}\n        </motion.div>\n      )}\n    </div>\n  )\n}",
    micro: true,
  },
  {
    id: "animated-input",
    name: "Animated Input",
    category: "Form Elements",
    description: "Input with floating label",
    tags: ["input","form"],
    code: "'use client'\n\nimport { motion } from 'framer-motion'\nimport { useState } from 'react'\nimport { Menu, X } from 'lucide-react'\n\nexport function AnimatedInput() {\n  return (\n    <div className=\"relative mt-8 min-w-[200px]\">\n      <input\n        type=\"text\"\n        id=\"animated-input\"\n        className=\"block px-2.5 pb-2.5 pt-4 w-full text-sm text-gray-900 bg-transparent rounded-lg border-2 border-gray-300 appearance-none dark:text-white dark:border-gray-600 dark:focus:border-blue-500 focus:outline-none focus:ring-0 focus:border-blue-600 peer\"\n        placeholder=\" \"\n      />\n      <label\n        htmlFor=\"animated-input\"\n        className=\"absolute text-sm text-gray-500 dark:text-gray-400 duration-300 transform -translate-y-4 scale-75 top-2 z-10 origin-[0] bg-white dark:bg-gray-900 px-2 peer-focus:px-2 peer-focus:text-blue-600 peer-focus:dark:text-blue-500 peer-placeholder-shown:scale-100 peer-placeholder-shown:-translate-y-1/2 peer-placeholder-shown:top-1/2 peer-focus:top-2 peer-focus:scale-75 peer-focus:-translate-y-4 left-1\"\n      >\n        Floating Label\n      </label>\n    </div>\n  )\n}",
  },
  {
    id: "toggle-switch",
    name: "Toggle Switch",
    category: "Form Elements",
    description: "Animated switch",
    tags: ["toggle","form"],
    code: "'use client'\n\nimport { motion } from 'framer-motion'\nimport { useState } from 'react'\nimport { Menu, X } from 'lucide-react'\n\nexport function ToggleSwitch() {\n  const [isOn, setIsOn] = useState(false)\n  return (\n    <div \n      className={`w-14 h-8 flex items-center rounded-full p-1 cursor-pointer transition-colors duration-300 ${isOn ? 'bg-green-500' : 'bg-gray-400'}`}\n      onClick={() => setIsOn(!isOn)}\n    >\n      <motion.div \n        className=\"bg-white w-6 h-6 rounded-full shadow-md\"\n        layout\n        transition={{ type: \"spring\", stiffness: 700, damping: 30 }}\n        style={{ marginLeft: isOn ? '1.5rem' : '0' }}\n      />\n    </div>\n  )\n}",
  },
  {
    id: "checkbox-neumorphic",
    name: "Neumorphic Checkbox",
    category: "Form Elements",
    description: "Checkbox with neumorphism",
    tags: ["checkbox","form"],
    code: "'use client'\n\nimport { motion } from 'framer-motion'\nimport { useState } from 'react'\nimport { Menu, X } from 'lucide-react'\n\nexport function CheckboxNeumorphic() {\n  const [checked, setChecked] = useState(false)\n  return (\n    <div \n      onClick={() => setChecked(!checked)}\n      className=\"w-8 h-8 rounded-md bg-gray-200 dark:bg-gray-800 shadow-[inset_2px_2px_5px_rgba(0,0,0,0.1),inset_-2px_-2px_5px_rgba(255,255,255,0.7)] dark:shadow-[inset_2px_2px_5px_rgba(0,0,0,0.5),inset_-2px_-2px_5px_rgba(255,255,255,0.1)] flex items-center justify-center cursor-pointer transition-all duration-200\"\n    >\n      <motion.div\n        initial={{ scale: 0 }}\n        animate={{ scale: checked ? 1 : 0 }}\n        className=\"w-4 h-4 bg-blue-500 rounded-sm\"\n      />\n    </div>\n  )\n}",
  },
  {
    id: "search-input",
    name: "Expanding Search",
    category: "Form Elements",
    description: "Search that expands on click",
    tags: ["search","input"],
    code: "'use client'\n\nimport { motion } from 'framer-motion'\nimport { useState } from 'react'\nimport { Menu, X } from 'lucide-react'\n\nexport function SearchInput() {\n  const [expanded, setExpanded] = useState(false)\n  return (\n    <motion.div\n      className=\"flex items-center bg-gray-100 dark:bg-gray-800 rounded-full px-4 py-2 border border-gray-200 dark:border-gray-700\"\n      initial={{ width: 48 }}\n      animate={{ width: expanded ? 200 : 48 }}\n      transition={{ type: \"spring\", stiffness: 300, damping: 25 }}\n    >\n      <div className=\"cursor-pointer text-gray-500\" onClick={() => setExpanded(!expanded)}>\n        <svg xmlns=\"http://www.w3.org/2000/svg\" className=\"h-5 w-5\" fill=\"none\" viewBox=\"0 0 24 24\" stroke=\"currentColor\"><path strokeLinecap=\"round\" strokeLinejoin=\"round\" strokeWidth={2} d=\"M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z\" /></svg>\n      </div>\n      {expanded && (\n        <motion.input\n          initial={{ opacity: 0 }}\n          animate={{ opacity: 1 }}\n          className=\"bg-transparent border-none outline-none ml-2 w-full text-sm placeholder-gray-400 dark:text-white\"\n          placeholder=\"Search...\"\n          autoFocus\n        />\n      )}\n    </motion.div>\n  )\n}",
  },
  {
    id: "neon-card",
    name: "Neon Card",
    category: "Cards & Containers",
    description: "Card with glowing neon hover",
    tags: ["card","hover"],
    code: "'use client'\n\nimport { motion } from 'framer-motion'\nimport { useState } from 'react'\nimport { Menu, X } from 'lucide-react'\n\nexport function NeonCard() {\n  return (\n    <div className=\"relative group w-64 h-80 rounded-xl bg-gray-900 overflow-hidden flex items-center justify-center\">\n      <div className=\"absolute inset-0 bg-gradient-to-r from-pink-500 via-purple-500 to-blue-500 opacity-0 group-hover:opacity-100 blur-xl transition-opacity duration-500\"></div>\n      <div className=\"absolute inset-[2px] bg-gray-900 rounded-xl z-10 flex flex-col items-center justify-center p-6 text-white text-center\">\n        <h3 className=\"text-xl font-bold mb-2 text-transparent bg-clip-text bg-gradient-to-r from-pink-400 to-blue-400\">Neon Card</h3>\n        <p className=\"text-sm text-gray-400\">Hover me to see the glowing neon borders react.</p>\n      </div>\n    </div>\n  )\n}",
  },
  {
    id: "flip-card",
    name: "Flip Card",
    category: "Cards & Containers",
    description: "3D flipping card",
    tags: ["card","3d"],
    code: "'use client'\n\nimport { motion } from 'framer-motion'\nimport { useState } from 'react'\nimport { Menu, X } from 'lucide-react'\n\nexport function FlipCard() {\n  return (\n    <div className=\"group w-64 h-80 [perspective:1000px]\">\n      <div className=\"relative w-full h-full transition-transform duration-700 [transform-style:preserve-3d] group-hover:[transform:rotateY(180deg)]\">\n        <div className=\"absolute w-full h-full [backface-visibility:hidden] bg-white dark:bg-gray-800 rounded-xl shadow-lg flex items-center justify-center text-xl font-bold border border-gray-200 dark:border-gray-700 text-gray-900 dark:text-white\">\n          Front Side\n        </div>\n        <div className=\"absolute w-full h-full [backface-visibility:hidden] [transform:rotateY(180deg)] bg-gradient-to-br from-indigo-500 to-purple-600 rounded-xl shadow-lg flex items-center justify-center text-white text-xl font-bold\">\n          Back Side\n        </div>\n      </div>\n    </div>\n  )\n}",
  },
  {
    id: "holographic-card",
    name: "Holographic Card",
    category: "Cards & Containers",
    description: "Card with holographic reflection",
    tags: ["card","holo"],
    code: "'use client'\n\nimport { motion } from 'framer-motion'\nimport { useState } from 'react'\nimport { Menu, X } from 'lucide-react'\n\nexport function HolographicCard() {\n  return (\n    <div className=\"relative w-64 h-80 rounded-2xl overflow-hidden cursor-pointer group shadow-2xl\">\n      <div className=\"absolute inset-0 bg-gray-900 z-0\"></div>\n      <div className=\"absolute inset-0 opacity-0 group-hover:opacity-20 transition-opacity duration-500 z-10 bg-[url('data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI4IiBoZWlnaHQ9IjgiPgogIDxyZWN0IHdpZHRoPSI4IiBoZWlnaHQ9IjgiIGZpbGw9IiNmZmYiIGZpbGwtb3BhY2l0eT0iMC4xIi8+CiAgPHBhdGggZD0iTTAgMEw4IDhaTTAgOEw4IDBaIiBzdHJva2U9IiMwMDAiIHN0cm9rZS1vcGFjaXR5PSIwLjEiLz4KPC9zdmc+')] bg-repeat mix-blend-color-dodge\"></div>\n      <div className=\"absolute inset-0 bg-gradient-to-tr from-transparent via-white/20 to-transparent translate-x-[-100%] group-hover:translate-x-[100%] transition-transform duration-1000 z-20\"></div>\n      <div className=\"relative z-30 w-full h-full p-6 flex flex-col items-start justify-end\">\n        <h2 className=\"text-2xl font-bold text-white mb-2 tracking-wide drop-shadow-md\">Holo Card</h2>\n        <p className=\"text-gray-300 text-sm\">Gleaming futuristic texture</p>\n      </div>\n    </div>\n  )\n}",
  },
  {
    id: "tilt-card",
    name: "Tilt Card",
    category: "Cards & Containers",
    description: "Card that tilts towards mouse",
    tags: ["card","tilt"],
    code: "'use client'\n\nimport { motion } from 'framer-motion'\nimport { useState } from 'react'\nimport { Menu, X } from 'lucide-react'\n\nexport function TiltCard() {\n  const [rotateX, setRotateX] = useState(0)\n  const [rotateY, setRotateY] = useState(0)\n\n  const handleMouseMove = (e: React.MouseEvent<HTMLDivElement>) => {\n    const rect = e.currentTarget.getBoundingClientRect()\n    const x = e.clientX - rect.left\n    const y = e.clientY - rect.top\n    const centerX = rect.width / 2\n    const centerY = rect.height / 2\n    \n    setRotateX(((y - centerY) / centerY) * -15)\n    setRotateY(((x - centerX) / centerX) * 15)\n  }\n\n  return (\n    <motion.div\n      className=\"w-64 h-80 bg-gradient-to-b from-blue-400 to-emerald-400 rounded-2xl p-1 shadow-xl [perspective:1000px]\"\n      onMouseMove={handleMouseMove}\n      onMouseLeave={() => { setRotateX(0); setRotateY(0) }}\n      animate={{ rotateX, rotateY }}\n      transition={{ type: \"spring\", stiffness: 300, damping: 30 }}\n      style={{ transformStyle: \"preserve-3d\" }}\n    >\n      <div className=\"w-full h-full bg-white/20 backdrop-blur-md rounded-xl p-6 flex flex-col justify-between\" style={{ transform: \"translateZ(30px)\" }}>\n        <div className=\"w-12 h-12 bg-white/50 rounded-full flex items-center justify-center\">\n          <svg className=\"w-6 h-6 text-white\" fill=\"none\" viewBox=\"0 0 24 24\" stroke=\"currentColor\"><path strokeLinecap=\"round\" strokeLinejoin=\"round\" strokeWidth={2} d=\"M13 10V3L4 14h7v7l9-11h-7z\" /></svg>\n        </div>\n        <div>\n          <h3 className=\"text-white font-bold text-xl drop-shadow-sm\">Tilt Effect</h3>\n          <p className=\"text-white/80 text-sm mt-1\">Move your mouse over me</p>\n        </div>\n      </div>\n    </motion.div>\n  )\n}",
  },
  {
    id: "swipe-button",
    name: "Swipe Button",
    category: "Buttons & CTAs",
    description: "Button with swipe hover effect",
    tags: ["button","hover"],
    code: "'use client'\n\nimport { motion } from 'framer-motion'\nimport { useState } from 'react'\nimport { Menu, X } from 'lucide-react'\n\nexport function SwipeButton() {\n  return (\n    <button className=\"group relative px-6 py-3 font-semibold text-white bg-gray-900 rounded-lg overflow-hidden\">\n      <span className=\"relative z-10\">Swipe Hover</span>\n      <div className=\"absolute inset-0 h-full w-0 bg-blue-600 transition-all duration-300 ease-out group-hover:w-full z-0\"></div>\n    </button>\n  )\n}",
  },
  {
    id: "download-button",
    name: "Download Button",
    category: "Buttons & CTAs",
    description: "Animated download states",
    tags: ["button","state"],
    code: "'use client'\n\nimport { motion } from 'framer-motion'\nimport { useState } from 'react'\nimport { Menu, X } from 'lucide-react'\n\nexport function DownloadButton() {\n  const [downloading, setDownloading] = useState(false)\n  return (\n    <button \n      onClick={() => { setDownloading(true); setTimeout(() => setDownloading(false), 2000) }}\n      className={`relative flex items-center justify-center px-6 py-3 font-bold text-white rounded-xl transition-all duration-300 ${downloading ? 'bg-green-500 w-14' : 'bg-indigo-600 w-44'}`}\n    >\n      {downloading ? (\n        <motion.svg initial={{ y: -10, opacity: 0 }} animate={{ y: 0, opacity: 1 }} className=\"w-6 h-6\" fill=\"none\" viewBox=\"0 0 24 24\" stroke=\"currentColor\"><path strokeLinecap=\"round\" strokeLinejoin=\"round\" strokeWidth={2} d=\"M5 13l4 4L19 7\" /></motion.svg>\n      ) : (\n        <span className=\"flex items-center gap-2\">\n          <span>Download</span>\n          <svg className=\"w-5 h-5\" fill=\"none\" viewBox=\"0 0 24 24\" stroke=\"currentColor\"><path strokeLinecap=\"round\" strokeLinejoin=\"round\" strokeWidth={2} d=\"M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4\" /></svg>\n        </span>\n      )}\n    </button>\n  )\n}",
  },
  {
    id: "glow-button",
    name: "Glow Button",
    category: "Buttons & CTAs",
    description: "Button with glowing aura",
    tags: ["button","glow"],
    code: "'use client'\n\nimport { motion } from 'framer-motion'\nimport { useState } from 'react'\nimport { Menu, X } from 'lucide-react'\n\nexport function GlowButton() {\n  return (\n    <button className=\"relative px-8 py-4 font-bold text-white bg-gray-800 rounded-full group\">\n      <span className=\"absolute inset-0 w-full h-full rounded-full bg-gradient-to-r from-blue-500 to-purple-500 blur-md opacity-70 group-hover:opacity-100 group-hover:blur-xl transition-all duration-300 -z-10\"></span>\n      Inner Glow\n    </button>\n  )\n}",
  },
  {
    id: "glitch-button",
    name: "Glitch Button",
    category: "Buttons & CTAs",
    description: "Cyberpunk glitch effect",
    tags: ["button","glitch"],
    code: "'use client'\n\nimport { motion } from 'framer-motion'\nimport { useState } from 'react'\nimport { Menu, X } from 'lucide-react'\n\nexport function GlitchButton() {\n  return (\n    <button className=\"relative px-8 py-3 bg-black text-white font-mono font-bold uppercase tracking-widest border border-white/20 group overflow-hidden\">\n      <span className=\"relative z-10 group-hover:hidden\">Cyberpunk</span>\n      <span className=\"absolute inset-0 items-center justify-center bg-red-600 font-mono font-bold uppercase tracking-widest hidden group-hover:flex transform -translate-x-1\">Cyberpunk</span>\n      <span className=\"absolute inset-0 items-center justify-center bg-blue-600 mix-blend-screen font-mono font-bold uppercase tracking-widest hidden group-hover:flex transform translate-x-1\">Cyberpunk</span>\n    </button>\n  )\n}",
  },
  {
    id: "spinner-loader",
    name: "Spinner Loader",
    category: "Loaders & Progress",
    description: "Classic glowing spinner",
    tags: ["loader","spinner"],
    code: "'use client'\n\nimport { motion } from 'framer-motion'\nimport { useState } from 'react'\nimport { Menu, X } from 'lucide-react'\n\nexport function SpinnerLoader() {\n  return (\n    <div className=\"w-12 h-12 rounded-full border-4 border-gray-200 border-t-blue-600 animate-spin\"></div>\n  )\n}",
  },
  {
    id: "dots-loader",
    name: "Bouncing Dots",
    category: "Loaders & Progress",
    description: "Bouncing dots loader",
    tags: ["loader","dots"],
    code: "'use client'\n\nimport { motion } from 'framer-motion'\nimport { useState } from 'react'\nimport { Menu, X } from 'lucide-react'\n\nexport function DotsLoader() {\n  return (\n    <div className=\"flex gap-2\">\n      <motion.div className=\"w-3 h-3 bg-indigo-500 rounded-full\" animate={{ y: [0, -10, 0] }} transition={{ duration: 0.6, repeat: Infinity, delay: 0 }} />\n      <motion.div className=\"w-3 h-3 bg-indigo-500 rounded-full\" animate={{ y: [0, -10, 0] }} transition={{ duration: 0.6, repeat: Infinity, delay: 0.2 }} />\n      <motion.div className=\"w-3 h-3 bg-indigo-500 rounded-full\" animate={{ y: [0, -10, 0] }} transition={{ duration: 0.6, repeat: Infinity, delay: 0.4 }} />\n    </div>\n  )\n}",
  },
  {
    id: "progress-bar-animated",
    name: "Animated Progress",
    category: "Loaders & Progress",
    description: "Gradient animated progress bar",
    tags: ["loader","progress"],
    code: "'use client'\n\nimport { motion } from 'framer-motion'\nimport { useState } from 'react'\nimport { Menu, X } from 'lucide-react'\n\nexport function ProgressBarAnimated() {\n  return (\n    <div className=\"w-64 h-4 bg-gray-200 rounded-full overflow-hidden\">\n      <motion.div \n        className=\"h-full bg-gradient-to-r from-cyan-400 to-blue-500\"\n        initial={{ width: \"0%\" }}\n        animate={{ width: \"100%\" }}\n        transition={{ duration: 3, repeat: Infinity, ease: \"linear\" }}\n      />\n    </div>\n  )\n}",
  },
  {
    id: "hexagon-loader",
    name: "Hexagon Loader",
    category: "Loaders & Progress",
    description: "SVG tracing hexagon loader",
    tags: ["loader","svg"],
    code: "'use client'\n\nimport { motion } from 'framer-motion'\nimport { useState } from 'react'\nimport { Menu, X } from 'lucide-react'\n\nexport function HexagonLoader() {\n  return (\n    <motion.svg className=\"w-16 h-16 text-purple-600\" viewBox=\"0 0 100 100\" animate={{ rotate: 360 }} transition={{ duration: 2, repeat: Infinity, ease: \"linear\" }}>\n      <polygon fill=\"none\" stroke=\"currentColor\" strokeWidth=\"4\" points=\"50,5 95,27.5 95,72.5 50,95 5,72.5 5,27.5\" strokeDasharray=\"300\" strokeDashoffset=\"150\">\n        <animate attributeName=\"stroke-dashoffset\" values=\"300;0\" dur=\"2s\" repeatCount=\"indefinite\" />\n      </polygon>\n    </motion.svg>\n  )\n}",
  },
  {
    id: "magic-navbar",
    name: "Magic Navbar",
    category: "Navigation",
    description: "Navbar with sliding active indicator",
    tags: ["nav","menu"],
    code: "'use client'\n\nimport { motion } from 'framer-motion'\nimport { useState } from 'react'\nimport { Menu, X } from 'lucide-react'\n\nexport function MagicNavbar() {\n  const [active, setActive] = useState(0)\n  const items = ['Home', 'Profile', 'Settings', 'Messages']\n  \n  return (\n    <div className=\"flex bg-white dark:bg-gray-800 rounded-2xl shadow-lg p-2 relative\">\n      {items.map((item, i) => (\n        <button key={item} onClick={() => setActive(i)} className=\"relative z-10 px-4 py-2 text-sm font-medium transition-colors duration-300 text-gray-700 dark:text-gray-300 hover:text-black dark:hover:text-white\">\n          {item}\n          {active === i && (\n            <motion.div layoutId=\"bubble\" className=\"absolute inset-0 bg-gray-200 dark:bg-gray-700 rounded-xl -z-10\" transition={{ type: \"spring\", stiffness: 500, damping: 30 }} />\n          )}\n        </button>\n      ))}\n    </div>\n  )\n}",
  },
  {
    id: "sidebar-menu",
    name: "Expandable Sidebar",
    category: "Navigation",
    description: "Sidebar that expands on hover",
    tags: ["nav","sidebar"],
    code: "'use client'\n\nimport { motion } from 'framer-motion'\nimport { useState } from 'react'\nimport { Menu, X } from 'lucide-react'\n\nexport function SidebarMenu() {\n  const [isOpen, setIsOpen] = useState(false)\n  return (\n    <motion.div \n      className=\"bg-indigo-600 text-white rounded-r-2xl flex flex-col justify-between py-6 overflow-hidden relative cursor-default\"\n      animate={{ width: isOpen ? 200 : 64 }}\n      transition={{ type: \"spring\", stiffness: 300, damping: 30 }}\n      onMouseEnter={() => setIsOpen(true)}\n      onMouseLeave={() => setIsOpen(false)}\n      style={{ height: '300px' }}\n    >\n      <div className=\"px-4 space-y-6\">\n        {[1, 2, 3].map(i => (\n          <div key={i} className=\"flex items-center gap-4 whitespace-nowrap cursor-pointer hover:text-indigo-200\">\n            <div className=\"w-8 h-8 rounded bg-white/20 flex-shrink-0\" />\n            <span className=\"font-medium\">Menu Item {i}</span>\n          </div>\n        ))}\n      </div>\n    </motion.div>\n  )\n}",
  },
  {
    id: "circular-menu",
    name: "Circular Menu",
    category: "Navigation",
    description: "Radial popup menu",
    tags: ["nav","radial"],
    code: "'use client'\n\nimport { motion } from 'framer-motion'\nimport { useState } from 'react'\nimport { Menu, X } from 'lucide-react'\n\nexport function CircularMenu() {\n  const [open, setOpen] = useState(false)\n  return (\n    <div className=\"relative w-32 h-32 flex items-center justify-center\">\n      <motion.button \n        onClick={() => setOpen(!open)}\n        className=\"w-12 h-12 bg-pink-500 rounded-full z-20 text-white flex items-center justify-center shadow-lg\"\n        animate={{ rotate: open ? 45 : 0 }}\n      >\n        <svg className=\"w-6 h-6\" fill=\"none\" viewBox=\"0 0 24 24\" stroke=\"currentColor\"><path strokeLinecap=\"round\" strokeLinejoin=\"round\" strokeWidth={2} d=\"M12 4v16m8-8H4\" /></svg>\n      </motion.button>\n      {[0, 1, 2, 3].map((i) => {\n        const angle = (i * Math.PI) / 2\n        return (\n          <motion.div\n            key={i}\n            className=\"absolute w-10 h-10 bg-white dark:bg-gray-800 rounded-full z-10 shadow-md flex items-center justify-center text-pink-500 cursor-pointer border border-pink-100 dark:border-gray-700\"\n            initial={{ x: 0, y: 0, opacity: 0 }}\n            animate={{ \n              x: open ? Math.cos(angle) * 45 : 0, \n              y: open ? Math.sin(angle) * 45 : 0, \n              opacity: open ? 1 : 0 \n            }}\n            transition={{ type: \"spring\", stiffness: 400, damping: 25, delay: i * 0.05 }}\n          >\n            {i + 1}\n          </motion.div>\n        )\n      })}\n    </div>\n  )\n}",
  },
  {
    id: "tooltip-menu",
    name: "Tooltip Action Menu",
    category: "Navigation",
    description: "Social links with tooltips",
    tags: ["nav","tooltip"],
    code: "'use client'\n\nimport { motion } from 'framer-motion'\nimport { useState } from 'react'\nimport { Menu, X } from 'lucide-react'\n\nexport function TooltipMenu() {\n  return (\n    <div className=\"flex gap-4\">\n      {['Twitter', 'GitHub', 'LinkedIn'].map((app) => (\n        <div key={app} className=\"group relative flex items-center justify-center w-12 h-12 bg-gray-100 dark:bg-gray-800 rounded-full cursor-pointer hover:bg-blue-500 hover:text-white transition-colors duration-300\">\n          <span className=\"text-xl font-bold\">{app[0]}</span>\n          <div className=\"absolute bottom-full mb-2 opacity-0 group-hover:opacity-100 translate-y-2 group-hover:translate-y-0 transition-all duration-300 bg-gray-900 text-white text-xs px-2 py-1 rounded\">\n            {app}\n            <div className=\"absolute top-full left-1/2 -translate-x-1/2 border-4 border-transparent border-t-gray-900\"></div>\n          </div>\n        </div>\n      ))}\n    </div>\n  )\n}",
  },
  {
    id: "pulsing-badge",
    name: "Pulsing Badge",
    category: "Badges & Tags",
    description: "Badge with pinging indicator",
    tags: ["badge","status"],
    code: "'use client'\n\nimport { motion } from 'framer-motion'\nimport { useState } from 'react'\nimport { Menu, X } from 'lucide-react'\n\nexport function PulsingBadge() {\n  return (\n    <div className=\"relative inline-flex\">\n      <span className=\"absolute flex h-3 w-3 -top-1 -right-1\">\n        <span className=\"animate-ping absolute inline-flex h-full w-full rounded-full bg-red-400 opacity-75\"></span>\n        <span className=\"relative inline-flex rounded-full h-3 w-3 bg-red-500\"></span>\n      </span>\n      <span className=\"px-3 py-1 bg-gray-100 dark:bg-gray-800 text-sm font-medium rounded-md border border-gray-200 dark:border-gray-700 text-gray-900 dark:text-gray-200\">Notifications</span>\n    </div>\n  )\n}",
  },
  {
    id: "glowing-tag",
    name: "Glowing Tag",
    category: "Badges & Tags",
    description: "Tag with active glowing shadow",
    tags: ["tag","active"],
    code: "'use client'\n\nimport { motion } from 'framer-motion'\nimport { useState } from 'react'\nimport { Menu, X } from 'lucide-react'\n\nexport function GlowingTag() {\n  return (\n    <div className=\"px-4 py-1.5 rounded-full text-xs font-bold text-white bg-gray-900 border border-green-500/50 shadow-[0_0_10px_rgba(34,197,94,0.3)] hover:shadow-[0_0_20px_rgba(34,197,94,0.5)] transition-shadow duration-300 tracking-wider\">\n      ACTIVE\n    </div>\n  )\n}",
  },
  {
    id: "gradient-border-badge",
    name: "Gradient Border Badge",
    category: "Badges & Tags",
    description: "Badge with gradient perimeter",
    tags: ["badge","gradient"],
    code: "'use client'\n\nimport { motion } from 'framer-motion'\nimport { useState } from 'react'\nimport { Menu, X } from 'lucide-react'\n\nexport function GradientBorderBadge() {\n  return (\n    <div className=\"p-[2px] rounded-lg bg-gradient-to-r from-fuchsia-500 to-cyan-500 shrink-0\">\n      <div className=\"px-3 py-1 bg-white dark:bg-gray-900 text-sm font-semibold rounded-md text-gray-900 dark:text-gray-100\">\n        Premium\n      </div>\n    </div>\n  )\n}",
  },
  {
    id: "status-indicator",
    name: "Status Indicator",
    category: "Badges & Tags",
    description: "Status pill with green dot",
    tags: ["badge","status"],
    code: "'use client'\n\nimport { motion } from 'framer-motion'\nimport { useState } from 'react'\nimport { Menu, X } from 'lucide-react'\n\nexport function StatusIndicator() {\n  return (\n    <div className=\"flex items-center gap-2 px-3 py-1.5 bg-green-50 dark:bg-green-900/20 text-green-700 dark:text-green-400 rounded-full text-sm font-medium border border-green-200 dark:border-green-800/30\">\n      <div className=\"w-2 h-2 rounded-full bg-green-500\"></div>\n      Operational\n    </div>\n  )\n}",
  },
  {
    id: "interactive-map",
    name: "Interactive Map",
    category: "Cards & Containers",
    description: "Animated map with interactive city tooltips",
    tags: ["map","pins","interaction"],
    code: "'use client'\n\nimport { motion } from 'framer-motion'\nimport { useState } from 'react'\nimport { Menu, X } from 'lucide-react'\n\nexport function InteractiveMap() {\n  const cities = [\n    { id: 1, x: 5, y: 67, name: 'Beach city', icon: '🏖️', anim: '' },\n    { id: 2, x: 32, y: 32, name: 'Flower city', icon: '🌷', anim: 'grow' },\n    { id: 3, x: 58, y: 83, name: 'Surf city', icon: '🏄', anim: 'slide' },\n    { id: 4, x: 65, y: 22, name: 'Capital city', icon: '🏛️', anim: '' },\n    { id: 5, x: 87, y: 58, name: 'Funland', icon: '🎢', anim: '' },\n    { id: 6, x: 94, y: 38, name: 'Coast city', icon: '🌊', anim: 'slide' },\n  ]\n\n  return (\n    <div className=\"relative w-full aspect-square max-w-[500px] border-radius-lg shadow-xl overflow-hidden bg-[#f5f0e5] group/map\">\n      <svg viewBox=\"0 0 500 500\" className=\"absolute inset-0 w-full h-full pointer-events-none\">\n        <path fill=\"#90daee\" d=\"M0,367.82c5.83-4.39,14.42-10.16,25.59-15.34,4.52-2.09,43.19-19.51,79.55-11.93,36.1,7.52,35.75,32.55,78.41,60.23,46.34,30.06,109.47,41.21,123.32,22.1,11.95-16.49-22.61-41.92-13.66-84.6,4.85-23.1,22.33-50.71,47.73-58.52,42.42-13.05,78.83,39.45,102.84,23.86,15.81-10.26.01-32.87,22.73-74.43,5.8-10.62,11.65-21.15,11.93-36.93.28-15.69-5.63-26.64-7.95-32.39-6.66-16.45-6.21-45.15,28.84-98.55.23,146.23.46,292.46.69,438.69H0v-132.18Z\" />\n      </svg>\n      \n      <div className=\"relative w-full h-full\">\n        {cities.map((city) => (\n          <div \n            key={city.id}\n            className=\"absolute group/city cursor-pointer\"\n            style={{ left: `${city.x}%`, top: `${city.y}%` }}\n          >\n            {/* Pin */}\n            <motion.div \n              className=\"relative -translate-x-1/2 -translate-y-1/2\"\n              whileHover={{ scale: 1.2 }}\n            >\n              <div className=\"text-xl filter drop-shadow-[0_1px_1px_rgba(0,0,0,0.5)]\">📍</div>\n              <div className=\"absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 text-black text-xs font-bold pointer-events-none\">•</div>\n            </motion.div>\n\n            {/* Label */}\n            <motion.div \n              initial={{ opacity: 0, y: -10 }}\n              whileHover={{ opacity: 1, y: -45 }}\n              className=\"absolute left-1/2 -translate-x-1/2 pointer-events-none z-50 whitespace-nowrap bg-[#00c080] border-2 border-white text-white px-3 py-1 rounded text-sm font-bold shadow-md flex items-center gap-2\"\n            >\n              {city.anim === 'grow' ? (\n                <motion.span initial={{ scale: 0 }} whileInView={{ scale: 1 }}>{city.icon}</motion.span>\n              ) : city.anim === 'slide' ? (\n                <motion.span initial={{ x: -20 }} whileInView={{ x: 0 }}>{city.icon}</motion.span>\n              ) : (\n                <span>{city.icon}</span>\n              )}\n              {city.name}\n            </motion.div>\n          </div>\n        ))}\n      </div>\n    </div>\n  )\n}",
  },
  {
    id: "progress-button-3d",
    name: "3D Progress Button",
    category: "Buttons & CTAs",
    description: "A 3D perspective button with progress bar animation",
    tags: ["button","3d","progress"],
    code: "'use client'\n\nexport function ProgressButton3D() {\n  return (\n    <>\n      <style>{`\n  .btn-96,\n  .btn-96 *,\n  .btn-96 :after,\n  .btn-96 :before,\n  .btn-96:after,\n  .btn-96:before {\n    border: 0 solid;\n    box-sizing: border-box;\n  }\n\n  .btn-96 {\n    -webkit-tap-highlight-color: transparent;\n    -webkit-appearance: button;\n    background-color: #000;\n    background-image: none;\n    color: #fff;\n    cursor: pointer;\n    font-family: ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont,\n      Segoe UI, Roboto, Helvetica Neue, Arial, Noto Sans, sans-serif,\n      Apple Color Emoji, Segoe UI Emoji, Segoe UI Symbol, Noto Color Emoji;\n    font-size: 100%;\n    line-height: 1.5;\n    margin: 0;\n    -webkit-mask-image: -webkit-radial-gradient(#000, #fff);\n    padding: 0;\n  }\n\n  .btn-96:disabled {\n    cursor: default;\n  }\n\n  .btn-96:-moz-focusring {\n    outline: auto;\n  }\n\n  .btn-96 svg {\n    display: block;\n    vertical-align: middle;\n  }\n\n  .btn-96 [hidden] {\n    display: none;\n  }\n\n  .btn-96 {\n    box-sizing: border-box;\n    display: block;\n    font-weight: 900;\n    -webkit-mask-image: none;\n    padding: 2rem 5rem;\n    perspective: 800px;\n    position: relative;\n    text-transform: uppercase;\n    transform-style: preserve-3d;\n  }\n\n  .btn-96 span {\n    background: #fff;\n    color: #000;\n    display: grid;\n    inset: 0;\n    place-items: center;\n    position: absolute;\n    transform: rotateX(0deg);\n    transform-origin: top center;\n    transition: 0.2s;\n  }\n\n  .btn-96:hover span {\n    transform: rotateX(35deg);\n  }\n\n  .btn-96:after,\n  .btn-96:before {\n    background: #ddd;\n    content: \"\";\n    height: 100%;\n    left: 0;\n    position: absolute;\n    top: 0;\n    transform: rotateX(0deg);\n    width: 100%;\n    z-index: -1;\n  }\n\n  .btn-96:after {\n    background: #ccc;\n    width: 0;\n  }\n\n  .btn-96:hover:after {\n    -webkit-animation: progress-bar 1.2s;\n    animation: progress-bar 1.2s;\n  }\n\n  @-webkit-keyframes progress-bar {\n    0% {\n      opacity: 1;\n      width: 0;\n    }\n\n    10% {\n      opacity: 1;\n      width: 15%;\n    }\n\n    25% {\n      opacity: 1;\n      width: 25%;\n    }\n\n    40% {\n      opacity: 1;\n      width: 35%;\n    }\n\n    55% {\n      opacity: 1;\n      width: 75%;\n    }\n\n    60% {\n      opacity: 1;\n      width: 100%;\n    }\n\n    to {\n      opacity: 0;\n      width: 100%;\n    }\n  }\n\n  @keyframes progress-bar {\n    0% {\n      opacity: 1;\n      width: 0;\n    }\n\n    10% {\n      opacity: 1;\n      width: 15%;\n    }\n\n    25% {\n      opacity: 1;\n      width: 25%;\n    }\n\n    40% {\n      opacity: 1;\n      width: 35%;\n    }\n\n    55% {\n      opacity: 1;\n      width: 75%;\n    }\n\n    60% {\n      opacity: 1;\n      width: 100%;\n    }\n\n    to {\n      opacity: 0;\n      width: 100%;\n    }\n  }\n      `}\n      </style>\n      <div className=\"flex items-center justify-center\">\n        <button className=\"btn-96\"><span>Button</span></button>\n      </div>\n    </>\n  )\n}",
  },
];

export const categories = [
  { name: 'Micro-interactions', description: 'Small, delightful interactions' },
  { name: 'Morphing Shapes', description: 'Components that change shape' },
  { name: 'Gradient Effects', description: 'Beautiful gradient animations' },
  { name: 'Form Elements', description: 'Interactive form controls' },
  { name: 'Cards & Containers', description: 'Layout containers and cards' },
  { name: 'Buttons & CTAs', description: 'Call to action elements' },
  { name: 'Navigation', description: 'Menus and navigation bars' },
  { name: 'Loaders & Progress', description: 'Loading states and progress bars' },
  { name: 'Badges & Tags', description: 'Status indicators and labels' }

];
